language: bash

before_script:
    - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx
    - mv shunit2-2.1.6/ shunit2
script:
    - bash aws-auth/tests/cli_test.sh